version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - DB_NAME=finance_manager

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=finance_manager

volumes:
  mongo_data: 